#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /logout
  methods: GET

dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index
